### ISSUE TITLE
Select loses all options 

### ISSUE THREAD

**Issue by JeffWScott** [TheComputerM/svelte-materialify#54]
If you select this same option twice in a Select component then the component becomes empty and clicking it does nothing. You can test on the demo site.

https://svelte-materialify.vercel.app/components/selects/

**Comment by rodgco** [comment]
I just examined the code and you can solve the problem by setting mandatory={true} in the Select.
Not sure if any use case would be impaired by hardwiring the "mandatory" prop to true at the Select component.

**Comment by TheComputerM** [comment]
Does this problem occur in any other group-like components such as ExpansionPanels?

**Comment by rodgco** [comment]
I've tried to replicate on ExpansionPanel but it doesn't seem to be a problem. Unfortunately I'm not able to understand to logic on ```ItemGroup``` to propose a solution.

**Comment by soft-decay** [comment]
You need to set `multiple={true}` if you pass an array to the `items` prop, otherwise you go in the [single item branch](https://github.com/TheComputerM/svelte-materialify/blob/3be086f60aa4c9748a622867b16540a6839d5506/packages/svelte-materialify/src/components/ItemGroup/ItemGroup.svelte#L40).

Arguably, maybe the component should just check if `items` is an array instead of checking if `multiple` is true.

**Comment by TheComputerM** [comment]
Fixed, need feedback of many people to make `mandatory` true by default.
